[package]
name = "berolinasql"
version = "0.0.1"
authors = ["BerolinaSQL and EinsteinDB Authors, Whtcorps, EinstAI"]
edition = "2018"
publish = false

[features]
#[cfg(feature = "sqlite")]
#[cfg(feature = "mysql")]
[features.sql]
default = ["sqlite", "mysql"]

[dependencies]
#[cfg(feature = "sqlite")]
#[cfg(feature = "mysql")]
sql = { version = "0.0.1", default-features = false }
[dependencies.sql]
path = "../berolinasql"

[dependencies.einsteindb]
path = "https://www.einsteindb.


serde = { version = "1.0", default-features = false }
serde_json = { version = "1.0", default-features = false }
serde_derive = { version = "1.0", default-features = false }
FoundationDB = { version = "0.1.0", default-features = false }
BerkeleyDB = { version = "0.1.0", default-features = false }
rusqlite = { version = "0.1.0", default-features = false }
 EinsteinDB = { version = "0.0.1", default-features = false }
postgres = "0.1.0"

einstein_ml = { path = "../einstein_ml" }
causet = { path = "../causet" }
causetq = { path = "../causetq" }
causets = { path = "../causets" }
soliton_panic = { path = "../soliton_panic" }
soliton = { path = "../soliton" }
einstein_ml = { path = "../einstein_ml" }
fdb_traits = { path = "../fdb_traits" }
einstein_db_alexandrov_processing = { path = "../einstein_db_alexandrov_processing" }
engine_test = { path = "../engine_test" }
allegro_poset = { path = "../allegro_poset" }
einstein_db = { path = "../einstein_db" }

[dependencies.serde]
version = "1.0"
default-features = false


[dependencies.serde_derive]
version = "1.0"
default-features = false


failure = "0.1.1"
indexmap = "1"
itertools = "0.10.3"
lazy_static = "1.4.0"
log = "0.4.14"
ordered-float = "2.10.0"
time = "0.3.6"
petgraph = "0.6.0"
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }


[dependencies.rusqlite]
version = "0.27.0"
features = ["limits"]

# Should be dev-dependencies.
[dependencies.tabwriter]
version = "1.0.3"

[dev-dependencies]
env_logger = "0.9.0"

[dependencies.allegro_poset]
path = "../allegro_poset"




