[package]
name = "berolinasql"
version = "0.0.1"
authors = ["BerolinaSQL and EinsteinDB Authors, Whtcorps, EinstAI"]
edition = "2018"
publish = false

[features]
default = []
syncable = ["serde", "serde_json", "serde_derive"]

[dependencies]
einstein_db = { path = "../einstein_db" }
einstein_ml = { path = "../einstein_ml" }

[dependencies.serde]
version = "1.0"
default-features = false


[dependencies.serde_derive]
version = "1.0"


failure = "0.1.1"
indexmap = "1"
itertools = "0.10.3"
lazy_static = "1.4.0"
log = "0.4.14"
ordered-float = "2.10.0"
time = "0.3.6"
petgraph = "0.6.0"
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }


[dependencies.rusqlite]
version = "0.27.0"
features = ["limits"]

# Should be dev-dependencies.
[dependencies.tabwriter]
version = "1.0.3"

[dev-dependencies]
env_logger = "0.9.0"

[dependencies.allegro_poset]
path = "../allegro_poset"




