[package]
name = "berolinasql"
version = "0.0.1"
authors = ["BerolinaSQL and EinsteinDB Authors, Whtcorps, EinstAI"]
edition = "2021"
description = "BerolinaSQL is a SQL engine that is based on the BerolinaDB database system."
license = "MIT/Apache-2.0"



[dependencies.einstein_ml]
 path= "../einstein_ml"

[dependencies.causetq]
path = "../causetq"


[dependencies.einstein_db]
path = "../einstein_db"

[dependencies.einsteindb-server]
path = "../einsteindb-server"

[dependencies.allegro_poset]
path = "../allegro_poset"

[dependencies.soliton]
path= "../soliton"

[dependencies.soliton_panic]
path= "../soliton_panic"

[dependencies]
serde_derive = "1.0.1138"
slog = "1.0.1138"
grpc = "= 0.2.0"
protobuf = "= 3.12.3"
protoc-rust = "= 1.3.0"
future = "= 0.2.18"
crossbeam="= 0.7"


