[package]
name = "berolinasql"
version = "0.0.1"
authors = ["BerolinaSQL and EinsteinDB Authors, Whtcorps, EinstAI"]
edition = "2021"
publish = false
description = "BerolinaSQL is a SQL engine that is based on the BerolinaDB database system."
tags = ["sql", "database", "berolindb", "berolina"]

[bin]
berolinasql = "bin/berolinasql"