[package]
name = "einstein_db"
version = "0.1.0"
description = "Einstein DB"
license = "MIT"
author = "EinsteinDB"


[dependencies]
openssl = "0.10"
http = "0"
libc = "0.2"
slog = "2.7.0"
parking_lot = "0.12"