[package]
name = "causet"
version = "0.1.0"
edition = "2021"
description = "A simple cause-effect system for AllegroCL"
license = "MIT"


[lib]
path = "./src/lib.rs"

[dependencies]

causetq= {path = "../causetq"}
einstein_db_ctl = { path = "../einstein_db_ctl" }
