[package]
name = "causet"
version = "0.1.0"
edition = "2021"
description = "A simple cause-effect system for AllegroCL"
license = "MIT"
url = "https://github.com/YosiSF/EinsteinDB/Causet"


[dependencies]
chrono = "0.4.19"
itertools = "0.10.3"
num = "0.4.0"
uuid = "1.1.2"


