[package]
name = "soliton"
version = "0.1.0"
authors = ["EinsteinDB Project"]
license = "MIT Licensed"
description = "Soliton is a distributed database system embedded to the EinsteinDB."
edition = "2021"


[dependencies]
failure = "0.1.1"
indexmap = "1"
itertools = "0.10.3"


