[package]
name = "soliton"
version = "0.1.0"
edition = "2021"

[dependencies]
failure = "0.1.1"
indexmap = "1"
itertools = "0.10.3"
lazy_static = "1.4.0"
log = "0.4"
ordered-float = "2.10.0"
time = "0.3.7"
petgraph = "0.6.0"
serde = { version = "1.0", optional = true }
serde_json = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }
serde_yaml = { version = "1.0", optional = true }


[dependencies.failure]
version = "0.1.1"

[dependencies.indexmap]
version = "1"


[dependencies.itertools]
version = "0.10.3"


[dependencies.lazy_static]
version = "1.4.0"


[dependencies.log]
version = "0.4"


[dependencies.ordered-float]
version = "2.10.0"


[dependencies.petgraph]
version = "0.6.0"


[dependencies.serde]
version = "1.0"


[dependencies.serde_json]
version = "1.0"


