[package]
name = "soliton"
version = "0.1.0"
authors = ["YosiSF aka whtcorps inc and einst ai inc"]
license = "MIT Licensed"
edition = "2021"

[dependencies]
failure = "0.1.1"
indexmap = "1"
itertools = "0.10.3"
lazy_static = "1.4.0"
log = "0.4"
ordered-float = "2.10.0"
time = "0.3.7"
petgraph = "0.6.0"
serde = { version = "1.0", optional = true }
serde_json = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }
serde_yaml = { version = "1.0", optional = true }


