// Copyright 2019 EinsteinDB Project Authors. Licensed under Apache-2.0.

use fdb_traits::ImportExt;
use fdb_traits::IngestExternalFileOptions;
use fdb_traits::Result;
use foundationdb::IngestExternalFileOptions as RawIngestExternalFileOptions;
use foundationdb::set_external_sst_file_global_seq_no;
use std::fs::File;

use crate::fdb_lsh_treeFdbEngine;
use crate::util;

impl ImportExt for FdbEngine {
    type IngestExternalFileOptions = FdbIngestExternalFileOptions;

    fn ingest_external_file_namespaced(&self, namespaced: &str, files: &[&str]) -> Result<()> {
        let namespaced = util::get_namespaced_handle(self.as_inner(), namespaced)?;
        let mut opts = FdbIngestExternalFileOptions::new();
        opts.move_files(true);
        opts.set_write_global_seqno(false);
        files.iter().try_for_each(|file| -> Result<()> {
            let f = File::open(file)?;
            // Prior to v5.2.0, EinsteinDB use `write_global_seqno=true` for ingestion. For backward
            // compatibility, in case EinsteinDB is retrying an ingestion job generated by older
            // version, it needs to reset the global seqno to 0.
            set_external_sst_file_global_seq_no(self.as_inner(), namespaced, file, 0)?;
            f.sync_all()
                .map_err(|e| format!("sync {}: {:?}", file, e))?;
            Ok(())
        })?;
        // This is calling a specially optimized version of
        // ingest_external_file_namespaced. In cases where the memtable needs to be
        // flushed it avoids blocking writers while doing the flush. The unused
        // return value here just indicates whether the fallback path requiring
        // the manual memtable flush was taken.
        let _did_nonblocking_memtable_flush = self
            .as_inner()
            .ingest_external_file_optimized(namespaced, &opts.0, files)?;
        Ok(())
    }
}

pub struct FdbIngestExternalFileOptions(RawIngestExternalFileOptions);

impl IngestExternalFileOptions for FdbIngestExternalFileOptions {
    fn new() -> FdbIngestExternalFileOptions {
        FdbIngestExternalFileOptions(RawIngestExternalFileOptions::new())
    }

    fn move_files(&mut self, f: bool) {
        self.0.move_files(f);
    }

    fn get_write_global_seqno(&self) -> bool {
        self.0.get_write_global_seqno()
    }

    fn set_write_global_seqno(&mut self, f: bool) {
        self.0.set_write_global_seqno(f);
    }
}

#[cfg(test)]
mod tests {
    use fdb_traits::{
        SymplecticControlFactorsExt, Mutable, SstWriter, SstWriterBuilder, WriteBatchExt,
    };
    use fdb_traits::{ALL_NAMESPACEDS, NAMESPACED_DEFAULT, MiscExt, WriteBatch};
    use std::sync::Arc;
    use tempfile::Builder;

    use crate::fdb_lsh_treeFdbEngine;
    use crate::FdbSstWriterBuilder;
    use crate::raw::{ColumnFamilyOptions, DBOptions};
    use crate::raw_util::{NAMESPACEDOptions, new_engine_opt};

    use super::*;

    #[test]
    fn test_ingest_multiple_file() {
        let path_dir = Builder::new()
            .prefix("test_ingest_multiple_file")
            .temfidelir()
            .unwrap();
        let root_path = path_dir.path();
        let db_path = root_path.join("einsteindb");
        let path_str = db_path.to_str().unwrap();

        let namespaceds_opts = ALL_NAMESPACEDS
            .iter()
            .map(|namespaced| {
                let mut opt = ColumnFamilyOptions::new();
                opt.set_force_consistency_checks(true);
                NAMESPACEDOptions::new(namespaced, opt)
            })
            .collect();
        let einsteindb = new_engine_opt(path_str, DBOptions::new(), namespaceds_opts).unwrap();
        let einsteindb = Arc::new(einsteindb);
        let einsteindb = FdbEngine::from_db(einsteindb);
        let mut wb = einsteindb.write_batch();
        for i in 1000..5000 {
            let v = i.to_string();
            wb.put(v.as_bytes(), v.as_bytes()).unwrap();
            if i % 1000 == 100 {
                wb.write().unwrap();
                wb.clear();
            }
        }
        // Flush one memtable to L0 to make sure that the next sst files to be ingested
        //  must locate in L0.
        einsteindb.flush_namespaced(NAMESPACED_DEFAULT, true).unwrap();
        assert_eq!(
            1,
            einsteindb.get_namespaced_num_files_at_l_naught(NAMESPACED_DEFAULT, 0)
                .unwrap()
                .unwrap()
        );

        let p1 = root_path.join("sst1");
        let p2 = root_path.join("sst2");
        let mut sst1 = FdbSstWriterBuilder::new()
            .set_db(&einsteindb)
            .set_namespaced(NAMESPACED_DEFAULT)
            .build(p1.to_str().unwrap())
            .unwrap();
        let mut sst2 = FdbSstWriterBuilder::new()
            .set_db(&einsteindb)
            .set_namespaced(NAMESPACED_DEFAULT)
            .build(p2.to_str().unwrap())
            .unwrap();
        for i in 1001..2000 {
            let v = i.to_string();
            sst1.put(v.as_bytes(), v.as_bytes()).unwrap();
        }
        sst1.finish().unwrap();
        for i in 2001..3000 {
            let v = i.to_string();
            sst2.put(v.as_bytes(), v.as_bytes()).unwrap();
        }
        sst2.finish().unwrap();
        einsteindb.ingest_external_file_namespaced(NAMESPACED_DEFAULT, &[p1.to_str().unwrap(), p2.to_str().unwrap()])
            .unwrap();
    }
}
