[package]
name = "einstein_db_ctl"
version = "0.1.0"
license = "MIT, Apache-2.0, BSD-3.0"
authors = ["Whtcorps Inc, The EinsteinDB Authors, EinstAI Inc, and OpenAI Inc"]
edition = "2021"



[dependencies]
gag = "1.0"
hex = "0.4"
causetq = { path = "../causetq" }
causet = { path = "../causet" }
causets = { path = "../causets" }
berolinasql = { path = "../berolinasql" }
chrono = "0.4"
crossbeam = "0.8"
tempfile = "3.0"
serde = "1.0.138"
structopt = "0.3"
futures = "0.3"
tokio = { version = "1.5", features = ["rt-multi-thread", "time"] }
libc = "0.2"
nix = "0.24.1"
rand = "0.8.5"
regex = "1"
serde_json = "1.0"
toml = "0.5"


[features]
serde = ["serde"]
serde_json = ["serde"]
serde_yaml = ["serde"]
serde_toml = ["serde"]
serde_json_derive = ["serde"]

