[package]
name = "einstein_ml"
license = "Apache-2.0"
version = "0.1.0"
edition = "2021"

[lib]
path = "../einstein_ml/lib.rs"



[dependencies]
num = "0.4.0"
ordered-float = "3.0.0"
pretty = { version = "0.11.2" }
