[package]
name = "allegro_poset"
version = "0.1.0"
edition = "2021"

# See more soliton_ids and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "allegro_poset"
path = "src/lib.rs"
crate-type = ["cdylib"]


[dependencies]
chrono = {version = "0.4.19", features=["serde"] }
enum-set = "0.0.8"
lazy_static = "1.4.0"
indexmap = "1.8.0"
serde = {version = "1.0.99", features=["derive"] }
uuid = "0.8.2"

[dependencies.ordered-float]
version = "2.9.0"
