[package]
name = "allegro_poset"
version = "0.1.0"
edition = "2021"
author = "AllegroCL EinsteinDB's team"
description = "AllegroCL Poset"
license = "MIT"


[dependencies]
einstein_db_alexandrov_processing = { path = "../einstein_db_alexandrov_processing" }
eingine_test = { path = "../engine_test" }
einstein_db = { path = "../einstein_db" }
berolinasql = { path = "../berolinasql" }
soliton_panic= { path = "../soliton_panic" }

byteorder = "1.2"
chrono = {version = "0.4.19", features=["serde"] }
tokio = "1.19.2"
enum-set = "0.0.8"
lazy_static = "1.4.0"
indexmap = "1.8.0"
serde = {version = "1.0.99", features=["derive"] }
uuid = "1.1.2"
libc = "0.2.54"
static_assertions = "1.0"


[dependencies.soliton]
version = "0.0.0"
features = ["serde"]









