[package]
name = "allegro_poset"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
einstein_db = { version = "0.1.0", features = ["einstein_db"] }