[package]
name = "einsteindb_server"
version = "0.1.0"
edition = "2021"
authors = ["einstein_db"]
description = "einstein_db server"
license = "MIT"
homepage = "https://www.einsteindb.com"
repository = "https://github.com/YosiSF/EinsteinDB"

[lib]
name = "einsteindb_server"
src = "src"
include = "include"