[package]
name = "soliton_panic"
version = "0.1.0"
description = "Soliton Panic"
edition = "2018"
publish = false


[dependencies]
soliton = { path = "../soliton" }


[workspace]
members = ["soliton_panic"]


[profile.release]
opt-level = 3
lto = true
debug = false
rpath = false
panic = "abort"


[profile.debug]
opt-level = 0
lto = false
debug = true
rpath = false
panic = "abort"





