[package]
name = "einstein_db_alexandrov_processv_processing"
version = "0.1.0"
authors = ["EinsteinDB Authors"]
edition = "2021"
license = "MIT Licensed"
url = "https://github.com/YosiSF/EinsteinDB.git"

[lib]
src = ["src/lib.rs"]

[dependencies]


[features]
default = ["einstein_db_alexandrov_processv_processing"]
einstein_db_alexandrov_processv_processing = []


[default]
features = ["default"]


[dev-dependencies]
einstein_db_alexandrov_processv_processing = { path = "../einstein_db_alexandrov_processv_processing" }



[build]
rustflags = ["-lm"]
link-args = ["-lm"]
rustc-link-lib = ["static=lm"]
rustc-link-search = ["/usr/lib/x86_64-linux-gnu/"]


[profile.release]
opt-level = "3"
lto = true
lto-codegen = true
lto-pre-link = true
lto-thin = true
lto-thin-lto = true




[profile.dev]
opt-level = "0"
lto = false
lto-codegen = false



[profile.test]
opt-level = "0"
lto = false
lto-codegen = false
test = true




