[package]
name = "einstein_db_alexandrov_processv_processing"
version = "0.1.0"
authors = ["EinsteinDB Authors"]
edition = "2021"
license = "MIT Licensed"
url = "https://github.com/YosiSF/EinsteinDB.git"

[[lib]]
#lib lives in the root of the package
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
src = ["src/lib.rs"]

[[bin]]
[dependencies]




