[package]
name = "einstein_db_alexandrov_processv_processing"
version = "0.1.0"
authors = ["EinsteinDB Authors"]
edition = "2021"
license = "MIT Licensed"
url = "https://github.com/YosiSF/EinsteinDB.git"

[lib]
src = ["src/lib.rs"]

#target



