[package]
name = "einstein_db_alexandrov_processv_processing"
version = "0.1.0"
authors = ["EinsteinDB Authors"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
einstein_db_alexandrov_processing = "0.1.0"
einstein_db = "0.1.0"
einstein_ml = "0.1.0"
berolinasql = "0.1.0"
causet = "0.1.0"
causetq = "0.1.0"
causets = "0.1.0"
einstein_db_ctl = "0.1.0"
soliton = "0.1.0"
soliton_panic = "0.1.0"
fdb_traits = "0.1.0"
