[package]
name = "einstein_db_alexandrov_processv_processing"
version = "0.1.0"
authors = ["EinsteinDB Authors"]
edition = "2021"
license = "MIT Licensed"
url = "https://github.com/YosiSF/EinsteinDB.git"


[dependencies]

einstein_db = { path = "../einstein_db" }

berolina_sql = { path = "../berolina_sql" }


causet = { path = "../causet" }
crate = { path = "../crate" }
crate_sql = { path = "../crate_sql" }
crate_sql_parser = { path = "../crate_sql_parser" }
crate_sql_syntax = { path = "../crate_sql_syntax" }
crate_sql_syntax_parser = { path = "../crate_sql_syntax_parser" }


crate_sql_syntax_parser_rust = { path = "../crate_sql_syntax_parser_rust" }




crate_sql_syntax_parser_rust_syntax = { path = "../crate_sql_syntax_parser_rust_syntax" }

