[package]
name = "einstein_db_alexandrov_processing"
version = "0.1.0"
authors = ["EinsteinDB Authors"]
edition = "2021"
license = "MIT Licensed"

[dependencies]
protobuf = "3.1.0"
crossbeam="0.8.1"
prost = "0.10.4"
prost-derive = "0.10.1"
serde = "= 1.0"