[package]
name = "causets"
version = "0.1.0"
edition = "2021"
description = "Causets is a tool for generating causality datasets for testing causality algorithms."
license = "MIT"



[dependencies]
futures = {version = "0.3"}
serde = { version = "0.9.0" }


