[package]
name = "causets"
version = "0.1.0"
edition = "2021"
author = "EinsteinDB Authors - @CavHack"
description = "Causets is a tool for generating causality datasets for testing causality algorithms."
license = "MIT"
homepage = "https://www.einsteindb.com"
repository = "https://www.github.com/YosiSF/EinsteinDB/Causets"


[dependencies]
#itertools = "^1.0"

[dependencies.einsteindb]
version = "^0.1"
