[package]
name = "causets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
causets-core = "0.1.0"
causets-cli = "0.1.0"

[build-dependencies]
causets = "^0.1"